### ISSUE TITLE
validate-website-static should not wrongly state that it validates localhost

### ISSUE THREAD

**Issue by stomar** [spk/validate-website#19]
validate-website-static should not by default report that it validates `http://localhost/`, while actually it validates files in the current directory (which probably are _not_ served under this URL).

```
$ validate-website-static
validating http://localhost/
...
```

Instead, it could simply report `validating files` or even only `validating`, for instance.

**Comment by spk** [comment]
We need a host for the relative URL but you are right its confusing and already reported in https://github.com/ruby/www.ruby-lang.org/issues/1977; will make a fix

**Comment by spk** [comment]
Released in https://rubygems.org/gems/validate-website/versions/1.9.1
